export * from './create-vacante.dto';
export * from './update-vacante.dto';
export * from './filter-vacante.dto';
export * from './create-postulante.dto';
export * from './update-postulante.dto';
export * from './filter-postulante.dto';
export * from './cambiar-estado.dto';
export * from './convertir-empleado.dto';
export * from './postulante-documento.dto';
